version: 2.1

orbs:
  node: circleci/node@5.0.3
  cypress: cypress-io/cypress@2.2.0

jobs:
  test_build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npx eslint src
      - run : 
          name : Run build
          command: npm run build

workflows:
  test_my_app:
    jobs:
      - cypress/install:
          install-command: npm install cypress
      - cypress/run:
          executor: cypress/base-14
          start: npm start
          wait-on: 'http://localhost:3000'
      - test_build